<a href="https://colab.research.google.com/github/NandiniLReddy/Pytorch/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics By Nandini Lokesh Reddy

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

False

## creating a empty tensor

## Scalar

In [ ]:
x1 = torch.empty(1) # 1 is the size, here 1 can be a scalar value

In [ ]:
print(x1) #output is the size allocated

tensor([-120.3074])


## Vector

In [ ]:
x2 = torch.empty(3) # 3 is the size, here 3 is 1D vector  [,,]

In [ ]:
print(x2)

tensor([-1.2031e+02,  4.4518e-41, -3.3191e-17])


## Matrix

2D, 3D, ............. Multi-Dimentional

In [ ]:
x3 = torch.empty(2,3) #(2,3) is the 2D matrix

In [ ]:
print(x3)

tensor([[-7.7054e+05,  3.1149e-41,  0.0000e+00],
        [ 1.1755e-38, -3.9553e-20,  3.1142e-41]])


In [ ]:
x4 = torch.empty(2,4,3) #(2,4,3) is the 3D matrix

In [ ]:
print(x4)

tensor([[[-6.5884e+05,  3.1149e-41,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 1.3452e-43,  0.0000e+00,  1.1210e-43],
         [ 0.0000e+00, -7.8569e+05,  3.1149e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


## creating a tensor with random values

In [ ]:
r1=torch.rand(3)
print(r1)

tensor([0.8963, 0.3423, 0.7835])


In [ ]:
r2=torch.rand(2,3)
print(r2)

tensor([[0.2328, 0.3284, 0.6247],
        [0.0986, 0.0164, 0.4179]])


## like numpy we can do certain operations like:

In [ ]:
z = torch.zeros(2,3)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
z1=torch.ones(2,3)
print(z1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## torch datatypes

In [ ]:
d1 = torch.rand(3) # default datatype is float32
print(d1.dtype)

torch.float32


In [ ]:
# we can initalize the dtype required as well
d2 =  torch.ones(4, dtype=torch.int)
print(d2)

tensor([1, 1, 1, 1], dtype=torch.int32)


In [ ]:
#rand is only used for float type

d3 = torch.rand(3, dtype=torch.double)
print(d3)

tensor([0.8411, 0.9982, 0.8172], dtype=torch.float64)


In [ ]:
# you can use randint for integers
d4 = torch.randint(5,10, (2,3))
print(d4.dtype)
print(d4)

torch.int64
tensor([[7, 6, 5],
        [5, 6, 5]])


In [ ]:
# we can also create tensors using list

l1 = torch.tensor([0.1,0.2])
print(l1)

tensor([0.1000, 0.2000])


## Basic operations

In [ ]:
a1 = torch.rand(2,2)
a2= torch.rand(2,2)
add = a1 + a2
# add = torch.add(a1,a2) #does the same as '+'
print(a1)
print(a2)
print(add)

tensor([[0.5912, 0.8287],
        [0.0109, 0.0486]])
tensor([[0.7840, 0.2652],
        [0.8950, 0.7441]])
tensor([[1.3752, 1.0940],
        [0.9059, 0.7927]])


In [ ]:
#inplace addition
a2.add_(a1) #values of a2 will be replaced with the result of addition operation
# print(a1)
print(a2)

tensor([[2.9708, 0.4933],
        [1.9178, 2.7999]])


for any function is there is '_' tailing then it is inplace operation

In [ ]:
sub = torch.sub(a1,a2) #does the same as '+'
print(a1)
print(a2)
print(sub)

tensor([[0.5912, 0.8287],
        [0.0109, 0.0486]])
tensor([[0.7840, 0.2652],
        [0.8950, 0.7441]])
tensor([[-0.1928,  0.5635],
        [-0.8841, -0.6955]])


In [ ]:
mul = torch.mul(a1,a2)
print(a1)
print(a2)
print(mul)

tensor([[0.5912, 0.8287],
        [0.0109, 0.0486]])
tensor([[0.7840, 0.2652],
        [0.8950, 0.7441]])
tensor([[0.4635, 0.2198],
        [0.0097, 0.0362]])


In [ ]:
div = torch.div(a1,a2)
print(a1)
print(a2)
print(div)

tensor([[0.5912, 0.8287],
        [0.0109, 0.0486]])
tensor([[0.7840, 0.2652],
        [0.8950, 0.7441]])
tensor([[0.7541, 3.1248],
        [0.0122, 0.0653]])


## Slicing

In [3]:
import torch
x=torch.rand(5,3) #all rows and 0th colum values only
print(x)
print(x[:,0])

tensor([[0.6289, 0.5163, 0.4372],
        [0.9098, 0.2220, 0.8335],
        [0.6283, 0.8015, 0.4811],
        [0.0612, 0.3719, 0.0141],
        [0.9557, 0.8695, 0.2142]])
tensor([0.6289, 0.9098, 0.6283, 0.0612, 0.9557])


In [5]:
print(x) #all columns and 1st row values only
print(x[1,:])

tensor([[0.6289, 0.5163, 0.4372],
        [0.9098, 0.2220, 0.8335],
        [0.6283, 0.8015, 0.4811],
        [0.0612, 0.3719, 0.0141],
        [0.9557, 0.8695, 0.2142]])
tensor([0.9098, 0.2220, 0.8335])


In [6]:
#to get the acutal value.[full value]
print(x[2,2].item())

0.48107820749282837


# Reshape

In [9]:
 x=torch.rand(4,4)
 print(x)
 y=x.view(16)
 print(y)
 print(y.size())

tensor([[0.0304, 0.5963, 0.0673, 0.4444],
        [0.0438, 0.2415, 0.4311, 0.9283],
        [0.2735, 0.6668, 0.5814, 0.5218],
        [0.6363, 0.8757, 0.4805, 0.0964]])
tensor([0.0304, 0.5963, 0.0673, 0.4444, 0.0438, 0.2415, 0.4311, 0.9283, 0.2735,
        0.6668, 0.5814, 0.5218, 0.6363, 0.8757, 0.4805, 0.0964])
torch.Size([16])


In [12]:
# you can add -1, to let pytorch determine the size based on the given one vlaue
y=x.view(-1,8)
print(y)
print(y.size())

tensor([[0.0304, 0.5963, 0.0673, 0.4444, 0.0438, 0.2415, 0.4311, 0.9283],
        [0.2735, 0.6668, 0.5814, 0.5218, 0.6363, 0.8757, 0.4805, 0.0964]])
torch.Size([2, 8])


# Numpy to torch tensor

In [17]:
import numpy as np
a= torch.ones(5)
print(a)
b=a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


#### if the tensor is in cpu, and we modify in gpu; then it also changes in the cpu as both GPU and CPU share the same memory

In [19]:
a.add_(1)
print(a) # you can see how b is also changed
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [20]:
a= np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


#### we cannot convert gpu tensor to numpy

# Gradients